//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoramientoEscritorio.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfertaAcademicaSW", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OfertaAcademicaSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreInstiField;
        
        private System.DateTime FechaDeInicioField;
        
        private System.DateTime FechaDeFinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreCurso {
            get {
                return this.NombreCursoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCursoField, value) != true)) {
                    this.NombreCursoField = value;
                    this.RaisePropertyChanged("NombreCurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreInsti {
            get {
                return this.NombreInstiField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreInstiField, value) != true)) {
                    this.NombreInstiField = value;
                    this.RaisePropertyChanged("NombreInsti");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaDeInicio {
            get {
                return this.FechaDeInicioField;
            }
            set {
                if ((this.FechaDeInicioField.Equals(value) != true)) {
                    this.FechaDeInicioField = value;
                    this.RaisePropertyChanged("FechaDeInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime FechaDeFin {
            get {
                return this.FechaDeFinField;
            }
            set {
                if ((this.FechaDeFinField.Equals(value) != true)) {
                    this.FechaDeFinField = value;
                    this.RaisePropertyChanged("FechaDeFin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BecaSW", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BecaSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionInstiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InstitucionNombre {
            get {
                return this.InstitucionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionNombreField, value) != true)) {
                    this.InstitucionNombreField = value;
                    this.RaisePropertyChanged("InstitucionNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DireccionInsti {
            get {
                return this.DireccionInstiField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionInstiField, value) != true)) {
                    this.DireccionInstiField = value;
                    this.RaisePropertyChanged("DireccionInsti");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfertaLaboralSW", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OfertaLaboralSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HabilidadesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private decimal SalarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEmpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Habilidades {
            get {
                return this.HabilidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.HabilidadesField, value) != true)) {
                    this.HabilidadesField = value;
                    this.RaisePropertyChanged("Habilidades");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NombreEmp {
            get {
                return this.NombreEmpField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEmpField, value) != true)) {
                    this.NombreEmpField = value;
                    this.RaisePropertyChanged("NombreEmp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioOfertaLaboralListarSW", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioOfertaLaboralListarSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfertaLaboralNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OfertaLaboralNombre {
            get {
                return this.OfertaLaboralNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.OfertaLaboralNombreField, value) != true)) {
                    this.OfertaLaboralNombreField = value;
                    this.RaisePropertyChanged("OfertaLaboralNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EmpresaNombre {
            get {
                return this.EmpresaNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaNombreField, value) != true)) {
                    this.EmpresaNombreField = value;
                    this.RaisePropertyChanged("EmpresaNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioOfertaAcademicaListarSW", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioOfertaAcademicaListarSW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreOfertaAcademicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitucionNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreOfertaAcademica {
            get {
                return this.NombreOfertaAcademicaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreOfertaAcademicaField, value) != true)) {
                    this.NombreOfertaAcademicaField = value;
                    this.RaisePropertyChanged("NombreOfertaAcademica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CursoNombre {
            get {
                return this.CursoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoNombreField, value) != true)) {
                    this.CursoNombreField = value;
                    this.RaisePropertyChanged("CursoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InstitucionNombre {
            get {
                return this.InstitucionNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionNombreField, value) != true)) {
                    this.InstitucionNombreField = value;
                    this.RaisePropertyChanged("InstitucionNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Ejercicio25WebServiceSoap")]
    public interface Ejercicio25WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.HelloWorldResponse HelloWorld(AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.HelloWorldResponse> HelloWorldAsync(AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logueo", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.LogueoResponse Logueo(AsesoramientoEscritorio.ServiceReference1.LogueoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logueo", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.LogueoResponse> LogueoAsync(AsesoramientoEscritorio.ServiceReference1.LogueoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AplicarOfertasLaborales", ReplyAction="*")]
        bool AplicarOfertasLaborales(int idOfertaLaboral, int usuarioid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AplicarOfertasLaborales", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AplicarOfertasLaboralesAsync(int idOfertaLaboral, int usuarioid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AplicarOfertasAcademicas", ReplyAction="*")]
        bool AplicarOfertasAcademicas(int idOfertaAcademica, int usuarioid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AplicarOfertasAcademicas", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AplicarOfertasAcademicasAsync(int idOfertaAcademica, int usuarioid);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaOfertaAcademicaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaOfertaAcademica", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponse ListaOfertaAcademica(AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaOfertaAcademica", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponse> ListaOfertaAcademicaAsync(AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaBecasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaBecas", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.ListaBecasResponse ListaBecas(AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaBecas", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaBecasResponse> ListaBecasAsync(AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaOfertasLaboralResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaOfertasLaboral", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponse ListaOfertasLaboral(AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaOfertasLaboral", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponse> ListaOfertasLaboralAsync(AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaUsuarioOfertasLaboralResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUsuarioOfertasLaboral", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponse ListaUsuarioOfertasLaboral(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUsuarioOfertasLaboral", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponse> ListaUsuarioOfertasLaboralAsync(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaUsuarioOfertaAcademicaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUsuarioOfertaAcademica", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponse ListaUsuarioOfertaAcademica(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaUsuarioOfertaAcademica", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponse> ListaUsuarioOfertaAcademicaAsync(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdUsuarioPorCorreo", ReplyAction="*")]
        AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponse ObtenerIdUsuarioPorCorreo(AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdUsuarioPorCorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponse> ObtenerIdUsuarioPorCorreoAsync(AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AsesoramientoEscritorio.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AsesoramientoEscritorio.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogueoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Logueo", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.LogueoRequestBody Body;
        
        public LogueoRequest() {
        }
        
        public LogueoRequest(AsesoramientoEscritorio.ServiceReference1.LogueoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogueoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LogueoRequestBody() {
        }
        
        public LogueoRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogueoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogueoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.LogueoResponseBody Body;
        
        public LogueoResponse() {
        }
        
        public LogueoResponse(AsesoramientoEscritorio.ServiceReference1.LogueoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogueoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LogueoResult;
        
        public LogueoResponseBody() {
        }
        
        public LogueoResponseBody(string LogueoResult) {
            this.LogueoResult = LogueoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaOfertaAcademicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaOfertaAcademica", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequestBody Body;
        
        public ListaOfertaAcademicaRequest() {
        }
        
        public ListaOfertaAcademicaRequest(AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaOfertaAcademicaRequestBody {
        
        public ListaOfertaAcademicaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaOfertaAcademicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaOfertaAcademicaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponseBody Body;
        
        public ListaOfertaAcademicaResponse() {
        }
        
        public ListaOfertaAcademicaResponse(AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaOfertaAcademicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.OfertaAcademicaSW[] ListaOfertaAcademicaResult;
        
        public ListaOfertaAcademicaResponseBody() {
        }
        
        public ListaOfertaAcademicaResponseBody(AsesoramientoEscritorio.ServiceReference1.OfertaAcademicaSW[] ListaOfertaAcademicaResult) {
            this.ListaOfertaAcademicaResult = ListaOfertaAcademicaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBecasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBecas", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaBecasRequestBody Body;
        
        public ListaBecasRequest() {
        }
        
        public ListaBecasRequest(AsesoramientoEscritorio.ServiceReference1.ListaBecasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaBecasRequestBody {
        
        public ListaBecasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBecasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBecasResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaBecasResponseBody Body;
        
        public ListaBecasResponse() {
        }
        
        public ListaBecasResponse(AsesoramientoEscritorio.ServiceReference1.ListaBecasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaBecasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.BecaSW[] ListaBecasResult;
        
        public ListaBecasResponseBody() {
        }
        
        public ListaBecasResponseBody(AsesoramientoEscritorio.ServiceReference1.BecaSW[] ListaBecasResult) {
            this.ListaBecasResult = ListaBecasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaOfertasLaboralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaOfertasLaboral", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequestBody Body;
        
        public ListaOfertasLaboralRequest() {
        }
        
        public ListaOfertasLaboralRequest(AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaOfertasLaboralRequestBody {
        
        public ListaOfertasLaboralRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaOfertasLaboralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaOfertasLaboralResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponseBody Body;
        
        public ListaOfertasLaboralResponse() {
        }
        
        public ListaOfertasLaboralResponse(AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaOfertasLaboralResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.OfertaLaboralSW[] ListaOfertasLaboralResult;
        
        public ListaOfertasLaboralResponseBody() {
        }
        
        public ListaOfertasLaboralResponseBody(AsesoramientoEscritorio.ServiceReference1.OfertaLaboralSW[] ListaOfertasLaboralResult) {
            this.ListaOfertasLaboralResult = ListaOfertasLaboralResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuarioOfertasLaboralRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuarioOfertasLaboral", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequestBody Body;
        
        public ListaUsuarioOfertasLaboralRequest() {
        }
        
        public ListaUsuarioOfertasLaboralRequest(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaUsuarioOfertasLaboralRequestBody {
        
        public ListaUsuarioOfertasLaboralRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuarioOfertasLaboralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuarioOfertasLaboralResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponseBody Body;
        
        public ListaUsuarioOfertasLaboralResponse() {
        }
        
        public ListaUsuarioOfertasLaboralResponse(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUsuarioOfertasLaboralResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.UsuarioOfertaLaboralListarSW[] ListaUsuarioOfertasLaboralResult;
        
        public ListaUsuarioOfertasLaboralResponseBody() {
        }
        
        public ListaUsuarioOfertasLaboralResponseBody(AsesoramientoEscritorio.ServiceReference1.UsuarioOfertaLaboralListarSW[] ListaUsuarioOfertasLaboralResult) {
            this.ListaUsuarioOfertasLaboralResult = ListaUsuarioOfertasLaboralResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuarioOfertaAcademicaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuarioOfertaAcademica", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequestBody Body;
        
        public ListaUsuarioOfertaAcademicaRequest() {
        }
        
        public ListaUsuarioOfertaAcademicaRequest(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaUsuarioOfertaAcademicaRequestBody {
        
        public ListaUsuarioOfertaAcademicaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaUsuarioOfertaAcademicaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaUsuarioOfertaAcademicaResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponseBody Body;
        
        public ListaUsuarioOfertaAcademicaResponse() {
        }
        
        public ListaUsuarioOfertaAcademicaResponse(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaUsuarioOfertaAcademicaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.UsuarioOfertaAcademicaListarSW[] ListaUsuarioOfertaAcademicaResult;
        
        public ListaUsuarioOfertaAcademicaResponseBody() {
        }
        
        public ListaUsuarioOfertaAcademicaResponseBody(AsesoramientoEscritorio.ServiceReference1.UsuarioOfertaAcademicaListarSW[] ListaUsuarioOfertaAcademicaResult) {
            this.ListaUsuarioOfertaAcademicaResult = ListaUsuarioOfertaAcademicaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIdUsuarioPorCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIdUsuarioPorCorreo", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequestBody Body;
        
        public ObtenerIdUsuarioPorCorreoRequest() {
        }
        
        public ObtenerIdUsuarioPorCorreoRequest(AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIdUsuarioPorCorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        public ObtenerIdUsuarioPorCorreoRequestBody() {
        }
        
        public ObtenerIdUsuarioPorCorreoRequestBody(string correo) {
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIdUsuarioPorCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIdUsuarioPorCorreoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponseBody Body;
        
        public ObtenerIdUsuarioPorCorreoResponse() {
        }
        
        public ObtenerIdUsuarioPorCorreoResponse(AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIdUsuarioPorCorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerIdUsuarioPorCorreoResult;
        
        public ObtenerIdUsuarioPorCorreoResponseBody() {
        }
        
        public ObtenerIdUsuarioPorCorreoResponseBody(string ObtenerIdUsuarioPorCorreoResult) {
            this.ObtenerIdUsuarioPorCorreoResult = ObtenerIdUsuarioPorCorreoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Ejercicio25WebServiceSoapChannel : AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ejercicio25WebServiceSoapClient : System.ServiceModel.ClientBase<AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap>, AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap {
        
        public Ejercicio25WebServiceSoapClient() {
        }
        
        public Ejercicio25WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ejercicio25WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ejercicio25WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ejercicio25WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.HelloWorldResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.HelloWorld(AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest inValue = new AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.HelloWorldRequestBody();
            AsesoramientoEscritorio.ServiceReference1.HelloWorldResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.HelloWorldResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.HelloWorldAsync(AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest inValue = new AsesoramientoEscritorio.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.HelloWorldRequestBody();
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.LogueoResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.Logueo(AsesoramientoEscritorio.ServiceReference1.LogueoRequest request) {
            return base.Channel.Logueo(request);
        }
        
        public string Logueo(string username, string password) {
            AsesoramientoEscritorio.ServiceReference1.LogueoRequest inValue = new AsesoramientoEscritorio.ServiceReference1.LogueoRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.LogueoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            AsesoramientoEscritorio.ServiceReference1.LogueoResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).Logueo(inValue);
            return retVal.Body.LogueoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.LogueoResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.LogueoAsync(AsesoramientoEscritorio.ServiceReference1.LogueoRequest request) {
            return base.Channel.LogueoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.LogueoResponse> LogueoAsync(string username, string password) {
            AsesoramientoEscritorio.ServiceReference1.LogueoRequest inValue = new AsesoramientoEscritorio.ServiceReference1.LogueoRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.LogueoRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).LogueoAsync(inValue);
        }
        
        public bool AplicarOfertasLaborales(int idOfertaLaboral, int usuarioid) {
            return base.Channel.AplicarOfertasLaborales(idOfertaLaboral, usuarioid);
        }
        
        public System.Threading.Tasks.Task<bool> AplicarOfertasLaboralesAsync(int idOfertaLaboral, int usuarioid) {
            return base.Channel.AplicarOfertasLaboralesAsync(idOfertaLaboral, usuarioid);
        }
        
        public bool AplicarOfertasAcademicas(int idOfertaAcademica, int usuarioid) {
            return base.Channel.AplicarOfertasAcademicas(idOfertaAcademica, usuarioid);
        }
        
        public System.Threading.Tasks.Task<bool> AplicarOfertasAcademicasAsync(int idOfertaAcademica, int usuarioid) {
            return base.Channel.AplicarOfertasAcademicasAsync(idOfertaAcademica, usuarioid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaOfertaAcademica(AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest request) {
            return base.Channel.ListaOfertaAcademica(request);
        }
        
        public AsesoramientoEscritorio.ServiceReference1.OfertaAcademicaSW[] ListaOfertaAcademica() {
            AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequestBody();
            AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaOfertaAcademica(inValue);
            return retVal.Body.ListaOfertaAcademicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaOfertaAcademicaAsync(AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest request) {
            return base.Channel.ListaOfertaAcademicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaResponse> ListaOfertaAcademicaAsync() {
            AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaOfertaAcademicaRequestBody();
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaOfertaAcademicaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.ListaBecasResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaBecas(AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest request) {
            return base.Channel.ListaBecas(request);
        }
        
        public AsesoramientoEscritorio.ServiceReference1.BecaSW[] ListaBecas() {
            AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaBecasRequestBody();
            AsesoramientoEscritorio.ServiceReference1.ListaBecasResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaBecas(inValue);
            return retVal.Body.ListaBecasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaBecasResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaBecasAsync(AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest request) {
            return base.Channel.ListaBecasAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaBecasResponse> ListaBecasAsync() {
            AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaBecasRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaBecasRequestBody();
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaBecasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaOfertasLaboral(AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest request) {
            return base.Channel.ListaOfertasLaboral(request);
        }
        
        public AsesoramientoEscritorio.ServiceReference1.OfertaLaboralSW[] ListaOfertasLaboral() {
            AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequestBody();
            AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaOfertasLaboral(inValue);
            return retVal.Body.ListaOfertasLaboralResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaOfertasLaboralAsync(AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest request) {
            return base.Channel.ListaOfertasLaboralAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralResponse> ListaOfertasLaboralAsync() {
            AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaOfertasLaboralRequestBody();
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaOfertasLaboralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaUsuarioOfertasLaboral(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest request) {
            return base.Channel.ListaUsuarioOfertasLaboral(request);
        }
        
        public AsesoramientoEscritorio.ServiceReference1.UsuarioOfertaLaboralListarSW[] ListaUsuarioOfertasLaboral() {
            AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequestBody();
            AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaUsuarioOfertasLaboral(inValue);
            return retVal.Body.ListaUsuarioOfertasLaboralResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaUsuarioOfertasLaboralAsync(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest request) {
            return base.Channel.ListaUsuarioOfertasLaboralAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralResponse> ListaUsuarioOfertasLaboralAsync() {
            AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertasLaboralRequestBody();
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaUsuarioOfertasLaboralAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaUsuarioOfertaAcademica(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest request) {
            return base.Channel.ListaUsuarioOfertaAcademica(request);
        }
        
        public AsesoramientoEscritorio.ServiceReference1.UsuarioOfertaAcademicaListarSW[] ListaUsuarioOfertaAcademica() {
            AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequestBody();
            AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaUsuarioOfertaAcademica(inValue);
            return retVal.Body.ListaUsuarioOfertaAcademicaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ListaUsuarioOfertaAcademicaAsync(AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest request) {
            return base.Channel.ListaUsuarioOfertaAcademicaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaResponse> ListaUsuarioOfertaAcademicaAsync() {
            AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ListaUsuarioOfertaAcademicaRequestBody();
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ListaUsuarioOfertaAcademicaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponse AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ObtenerIdUsuarioPorCorreo(AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest request) {
            return base.Channel.ObtenerIdUsuarioPorCorreo(request);
        }
        
        public string ObtenerIdUsuarioPorCorreo(string correo) {
            AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequestBody();
            inValue.Body.correo = correo;
            AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponse retVal = ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ObtenerIdUsuarioPorCorreo(inValue);
            return retVal.Body.ObtenerIdUsuarioPorCorreoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponse> AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap.ObtenerIdUsuarioPorCorreoAsync(AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest request) {
            return base.Channel.ObtenerIdUsuarioPorCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoResponse> ObtenerIdUsuarioPorCorreoAsync(string correo) {
            AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest inValue = new AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequest();
            inValue.Body = new AsesoramientoEscritorio.ServiceReference1.ObtenerIdUsuarioPorCorreoRequestBody();
            inValue.Body.correo = correo;
            return ((AsesoramientoEscritorio.ServiceReference1.Ejercicio25WebServiceSoap)(this)).ObtenerIdUsuarioPorCorreoAsync(inValue);
        }
    }
}
