//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoramientoEscritorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesoramiento
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int AsesorId { get; set; }
        public int UsuarioId { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Asesor Asesor { get; set; }
    }
}
