//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsesoramientoEscritorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Asesoramientos = new HashSet<Asesoramiento>();
            this.ResultadosDePruebas = new HashSet<ResultadoDePrueba>();
            this.Usuarios_OfertasAcademicas = new HashSet<Usuario_OfertaAcademica>();
            this.Usuarios_Becas = new HashSet<Usuario_Beca>();
            this.Usuarios_OfertasLaborales = new HashSet<Usuario_OfertaLaboral>();
            this.Usuarios_Cursos = new HashSet<Usuario_Curso>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int GeneroId { get; set; }
        public int DepartamentoId { get; set; }
        public int TipoId { get; set; }
        public string PreferenciasVocacionales { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Genero Genero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asesoramiento> Asesoramientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultadoDePrueba> ResultadosDePruebas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_OfertaAcademica> Usuarios_OfertasAcademicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Beca> Usuarios_Becas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_OfertaLaboral> Usuarios_OfertasLaborales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Curso> Usuarios_Cursos { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
